# Generated by Django 5.2.7 on 2026-09-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0007_alter_helperprofile_rating_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helperprofile',
            old_name='adhaar_verified',
            new_name='id_verified',
        ),
        migrations.RenameField(
            model_name='helperprofile',
            old_name='area',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='helperprofile',
            name='aadhaar_card',
        ),
        migrations.RemoveField(
            model_name='helperprofile',
            name='address_proof',
        ),
        migrations.RemoveField(
            model_name='helperprofile',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='helperprofile',
            name='pan_verified',
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='back_card',
            field=models.FileField(blank=True, null=True, upload_to='helper_docs/back/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='front_card',
            field=models.FileField(blank=True, null=True, upload_to='helper_docs/front/%Y/%m/'),
        ),
    ]
